// Objective-C API for talking to gomobiletest/go/greeter Go package.
//   gobind -lang=objc gomobiletest/go/greeter
//
// File is generated by gobind. Do not edit.

#ifndef __Greeter_H__
#define __Greeter_H__

@import Foundation;
#include "Universe.objc.h"


@class GreeterGreeter;
@protocol GreeterPrinter;
@class GreeterPrinter;

@protocol GreeterPrinter <NSObject>
- (void)printSomething:(NSString*)s;
@end

@interface GreeterGreeter : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init:(id<GreeterPrinter>)printer;
- (void)greet:(NSString*)name;
@end

FOUNDATION_EXPORT GreeterGreeter* GreeterNewGreeter(id<GreeterPrinter> printer);

@class GreeterPrinter;

@interface GreeterPrinter : NSObject <goSeqRefInterface, GreeterPrinter> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)printSomething:(NSString*)s;
@end

#endif
